id: P006997
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 12:35:05.840966
source_metadata:
  id: bdr:W4CZ1040
  title: རས་ཆུང་རྡོ་རྗེ་གྲགས་པའི་རྣམ་ཐར་རགས་བསྡུས་མགུར་རྣམ་རྒྱས་པ།
  author: ''
  volumes:
    bc8d5e7206564131abad918b3ed4e470:
      image_group_id: I1KG13516
      title: Volume 1 of ras chung rdo rje grags pa'i rnam thar rags bsdus mgur rnam
        rgyas pa/
      volume_number: 1
      total_pages: 190
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
