id: P006997
initial_creation_type: ocr
source_metadata:
  id: bdr:W4CZ1040
  title: རས་ཆུང་རྡོ་རྗེ་གྲགས་པའི་རྣམ་ཐར་རགས་བསྡུས་མགུར་རྣམ་རྒྱས་པ།
  author: ''
  volumes:
    408c6ad57d27466483287aafa53353a3:
      image_group_id: I1KG13516
      title: ''
      volume_number: 1
      total_pages: 190
ebook_metadata:
  title: རས་ཆུང་རྡོ་རྗེ་གྲགས་པའི་རྣམ་ཐར་རགས་བསྡུས་མགུར་རྣམ་རྒྱས་པ།
  author: ''
  sku: P006997
  cover: cover.jpg
  layers:
  - pagination
