id: IAC4FDA4A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T13:43:43+00:00'
last_modified: '2022-06-08T10:56:08.202848+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4CZ1040
  title: རས་ཆུང་རྡོ་རྗེ་གྲགས་པའི་རྣམ་ཐར་རགས་བསྡུས་མགུར་རྣམ་རྒྱས་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    7EA0:
      image_group_id: I1KG13516
      title: Volume 1 of ras chung rdo rje grags pa'i rnam thar rags bsdus mgur rnam
        rgyas pa/
      total_pages: 190
      order: 1
      base_file: 7EA0.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
